sudo: required
services:
  - docker

before_install:
  - docker build -t multi-container-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run multi-container-docker npm test -- --coverage

after_success:
  - docker build -t multi-container-docker-client ./client
  - docker build -t multi-container-docker-nginx ./nginx
  - docker build -t multi-container-docker-server ./server
  - docker build -t multi-container-docker-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push multi-container-docker-client
  - docker push multi-container-docker-nginx
  - docker push multi-container-docker-server
  - docker push multi-container-docker-worker
